### PR TITLE
Prettier: Add prettier integration to eslint config

### PR DESCRIPTION
**Pull request by Shadowfiend**
This should let us bundle everything together and use it downstream as one package.

### CODE REVIEW

**Comment by Shadowfiend** [comment]
Okayyy made a bunch more tweaks here and ran this against tbtc (not pushed yet) and tbtc.js (see the above linked Lintify PR).

**Comment by Shadowfiend** [comment]
Going to turbomerge here given it's working across several places and blocking some work. Still open to remarks @liamzebedee, we can always update + bump the version if needed.

**Comment by liamzebedee** [comment]
This PR looked good @Shadowfiend. Was waiting to test integration.

**Comment by Shadowfiend** [comment]
Awesome, thanks for the follow up 🙇

**Pull request merged**
